// This file is autogenerated from ../../uart-to-azureiot.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// SEND_BUTTON
#define SEND_BUTTON MT3620_RDB_BUTTON_A

// ARDUINO_UART
#define ARDUINO_UART MT3620_RDB_HEADER2_ISU0_UART

